import type { Metadata } from "next";
import { Antonio, Hanken_Grotesk } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

const antonio = Antonio({
  weight: '100',
  subsets: ['latin'],
})


const hanken_grotesk = Hanken_Grotesk({
  weight: '500',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hanken_grotesk.className} bg-soft-black`}>{children}</body>
    </html>
  );
}
