import type { Metadata } from "next";
import { Antonio } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

const antonio = Antonio({
  weight: '700',
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={antonio.className}>{children}</body>
    </html>
  );
}
